name: Mauvents
author: Tulir293
main: net.maunium.bukkit.Mauvents.Mauvents
website: http://maunium.net
version: 0.1
depend: [Maussentials]
commands:
  mauvents:
    description: Main command for admins
    permission: mauvents.admin
    permission-message: "§4[§cMauvents§4]§c You do not have <permission>"
    usage: "§4[§cMauvents§4]§c Usage: /<command> <game> <start/setspawn> [spawn type]"
    aliases: [eventsadmin, eventadmin, mauventadmin, maueventadmin, maueventsadmin]
  maubrackets:
    description: Join/leave brackets
    permission: mauvents.play.brackets
    permission-message: "§4[§cMauvents§4]§c You do not have <permission>"
    usage: "§4[§cMauvents§4]§c Usage: /<command> [join/leave]"
    aliases: [brackets]
  maulastmanstanding:
    description: Join/leave LMS.
    permission: mauvents.play.lms
    usage: "§4[§cMauvents§4]§c Usage: /<command> [join/leave]"
    aliases: [lastmanstanding, maulms, lms]
  maulastteamstanding:
    description: Join/leave LTS.
    permission: mauvents.play.lts
    usage: "§4[§cMauvents§4]§c Usage: /<command> [join/leave]"
    aliases: [lastteamstanding, maults, lts]
permissions:
  mauvents.admin:
    description: Be an admin
    default: OP
  mauvents.play.brackets:
    description: Play brackets
    default: true
  mauvents.play.lms:
    description: Play LMS
    default: true
  mauvents.play.lts:
    description: Play LTS
    default: true